# 应用名称
spring:
  application:
    name: springbootdemo
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    hikari:
      max-lifetime: 1800000
      connection-timeout: 5000
      idle-timeout: 360000
      maximum-pool-size: 12
      minimum-idle: 4
      connection-test-query: /**ping*/

# 应用服务 WEB 访问端口
server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

